# Generated by Django 5.1.3 on 2024-11-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('isopen', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lockerslist',
                'managed': False,
            },
        ),
    ]
